# -*- coding: utf-8 -*-
from pathlib import Path as _Path

__version__ = _Path(__file__).with_name("VERSION").read_text(encoding="utf-8").strip()
del _Path

from .catalogless_game_drop_patch import apply_patch as _apply_catalogless_game_drop_patch
from .catalogless_game_drop_runtime_patch import apply_patch as _apply_catalogless_game_drop_runtime_patch
from .catalogless_game_drop_session_latch_patch import apply_patch as _apply_catalogless_game_drop_session_latch_patch
from .channel_points_context_patch import apply_patch as _apply_channel_points_context_patch
from .completed_game_drop_guard_patch import apply_patch as _apply_completed_game_drop_guard_patch
from .configured_drop_game_priority_patch import apply_patch as _apply_configured_drop_game_priority_patch
from .discord_format_patch import apply_patch as _apply_discord_format_patch
from .drop_claim_game_patch import apply_patch as _apply_drop_claim_game_patch
from .drop_game_main_list_preference_patch import apply_patch as _apply_drop_game_main_list_preference_patch
from .drop_games_patch import apply_patch as _apply_drop_games_patch
from .drop_gql_queries_patch import apply_patch as _apply_drop_gql_queries_patch
from .drop_priority_order_patch import apply_patch as _apply_drop_priority_order_patch
from .dual_game_drop_idle_slot_patch import apply_patch as _apply_dual_game_drop_idle_slot_patch
from .explicit_game_drop_discovery_patch import apply_patch as _apply_explicit_game_drop_discovery_patch
from .finish_started_drops_patch import apply_patch as _apply_finish_started_drops_patch
from .fork_branding_patch import apply_patch as _apply_fork_branding_patch
from .game_drop_handoff_patch import apply_patch as _apply_game_drop_handoff_patch
from .game_drop_progress_verification_patch import apply_patch as _apply_game_drop_progress_verification_patch
from .inventory_campaign_recovery_patch import apply_patch as _apply_inventory_campaign_recovery_patch
from .playback_access_token_patch import apply_patch as _apply_playback_access_token_patch
from .status_dashboard_patch import apply_patch as _apply_status_dashboard_patch
from .status_dashboard_webhook_patch import apply_patch as _apply_status_dashboard_webhook_patch
from .status_dashboard_enhancements_patch import apply_patch as _apply_status_dashboard_enhancements_patch
from .status_dashboard_drop_reason_patch import apply_patch as _apply_status_dashboard_drop_reason_patch
from .status_dashboard_clock_patch import apply_patch as _apply_status_dashboard_clock_patch
from .status_dashboard_error_safety_patch import apply_patch as _apply_status_dashboard_error_safety_patch
from .status_dashboard_identity_patch import apply_patch as _apply_status_dashboard_identity_patch
from .stream_state_transition_patch import apply_patch as _apply_stream_state_transition_patch
from .watch_notifications_patch import apply_patch as _apply_watch_notifications_patch
from .watch_streak_persistence_patch import apply_patch as _apply_watch_streak_persistence_patch

_apply_fork_branding_patch()
_apply_drop_gql_queries_patch()
_apply_channel_points_context_patch()
_apply_discord_format_patch()
_apply_drop_claim_game_patch()
_apply_playback_access_token_patch()
_apply_stream_state_transition_patch()
_apply_watch_streak_persistence_patch()
_apply_inventory_campaign_recovery_patch()
_apply_drop_games_patch()
_apply_drop_game_main_list_preference_patch()
_apply_finish_started_drops_patch()
_apply_configured_drop_game_priority_patch()
_apply_drop_priority_order_patch()
_apply_explicit_game_drop_discovery_patch()
_apply_watch_notifications_patch()
_apply_status_dashboard_patch()
_apply_status_dashboard_webhook_patch()
_apply_status_dashboard_enhancements_patch()
_apply_status_dashboard_drop_reason_patch()
_apply_catalogless_game_drop_patch()
_apply_game_drop_handoff_patch()
_apply_completed_game_drop_guard_patch()
_apply_catalogless_game_drop_runtime_patch()
_apply_catalogless_game_drop_session_latch_patch()
_apply_game_drop_progress_verification_patch()
_apply_dual_game_drop_idle_slot_patch()
_apply_status_dashboard_clock_patch()
_apply_status_dashboard_error_safety_patch()
_apply_status_dashboard_identity_patch()
del _apply_catalogless_game_drop_patch
del _apply_catalogless_game_drop_runtime_patch
del _apply_catalogless_game_drop_session_latch_patch
del _apply_channel_points_context_patch
del _apply_completed_game_drop_guard_patch
del _apply_configured_drop_game_priority_patch
del _apply_discord_format_patch
del _apply_drop_claim_game_patch
del _apply_drop_game_main_list_preference_patch
del _apply_drop_games_patch
del _apply_drop_gql_queries_patch
del _apply_drop_priority_order_patch
del _apply_dual_game_drop_idle_slot_patch
del _apply_explicit_game_drop_discovery_patch
del _apply_finish_started_drops_patch
del _apply_fork_branding_patch
del _apply_game_drop_handoff_patch
del _apply_game_drop_progress_verification_patch
del _apply_inventory_campaign_recovery_patch
del _apply_playback_access_token_patch
del _apply_status_dashboard_clock_patch
del _apply_status_dashboard_drop_reason_patch
del _apply_status_dashboard_enhancements_patch
del _apply_status_dashboard_error_safety_patch
del _apply_status_dashboard_identity_patch
del _apply_status_dashboard_patch
del _apply_status_dashboard_webhook_patch
del _apply_stream_state_transition_patch
del _apply_watch_notifications_patch
del _apply_watch_streak_persistence_patch

from .TwitchChannelPointsMiner import TwitchChannelPointsMiner

__all__ = [
    "TwitchChannelPointsMiner",
    "__version__",
]
